apiVersion: v1
kind: Service
metadata:
  name: {{ include "daemonset-annotator.fullname" . }}
  labels:
    {{- include "daemonset-annotator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: https
      protocol: TCP
      name: http
  selector:
    {{- include "daemonset-annotator.selectorLabels" . | nindent 4 }}
