apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "daemonset-annotator.fullname" . }}-config
  labels:
    {{- include "daemonset-annotator.labels" . | nindent 4 }}
data:
  config.yaml: |-
    server:
      port: {{ .Values.config.server.port }}
      certificate: {{ .Values.config.server.certificate }}
      key: {{ .Values.config.server.key }}
    annotations:
{{ toYaml .Values.config.annotations | indent 6 }} 
